version: '3.9'
services:
  api:
    build: ./Backend
    ports:
      - 5000:5000
    image: bert-api-image
  frontend:
    build:
      context: ./Frontend
      target: production
    ports:
      - 80:3000
    image: bert-front-image
    